### ISSUE TITLE
affe-find and embark-dired-jump

### ISSUE THREAD

**Issue by jsilve24** [minad/affe#21]
I am having a problem with embark-dired-jump only when using affe-find (not when using find-file or others). 

**My Setup:** 
```
(package! affe
  :recipe (:host github :repo "minad/affe")
  :pin "b7d51c5e5426863b39809fa6ebce5f54696b50d6")

(use-package! affe
  :config
  ;; Manual preview key for `affe-grep'
  (consult-customize affe-grep :preview-key (kbd "M-.")))

(map! :after consult
      :leader
      :desc "affe find" "fa" (lambda () (interactive) (affe-find "~/")))
```

**What I am getting**

If I am editing a buffer at path: `~/foo/bar.txt` and I run `(affe-find "~/")` and try to use embark-dired-jump on a candidate file located at `~/baz/bat.md` I get the following error:

`embark PCH: (file-missing "Opening directory" "No such file or directory" "/home/[my-username]/foo/home/[my-username]/baz/bat.md")`

This works fine if my current working directory is "~/" but if I am visiting a file in a sub-directory I get the above error.

**Comment by minad** [comment]
Can you try to use an absolute path without tilde? But it shouldn't make a difference.

I assume the problem is https://github.com/oantolin/embark/issues/362 and should be fixed in Embark.

**Comment by jsilve24** [comment]
Wow, thanks for finding that so quickly. As you expected writing out "/home/jds6696/" doesn't change anything. I will wait for the upstream fix. Thanks alot! I imagine this should be closed here?

**Comment by jsilve24** [comment]
Hi @minad 
Acctually the issue is still remaining even when using the most recent version of embark. Do you think it could be an issue with affe itself?

**Comment by minad** [comment]
I cannot reproduce the issue anymore.

**Comment by minad** [comment]
Status?
